import GridBg from '@/components/layout/gridBg';
import Sidebar from '@/components/layout/sidebar';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Home | Nondenoic',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-base min-h-[4000px] text-light-text dark:text-dark-text`}>
        <Providers>
          <GridBg />
          <Sidebar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
